# Generated by Django 5.2.4 on 2025-07-29 22:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#0EC6EB', help_text='Hex color code for calendar display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='Brief description for calendar view', max_length=200)),
                ('event_type', models.CharField(choices=[('service', 'Church Service'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('social', 'Social Event'), ('outreach', 'Outreach'), ('meeting', 'Meeting'), ('special', 'Special Event'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10)),
                ('recurrence_end_date', models.DateField(blank=True, help_text='When to stop recurring events', null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('online_link', models.URLField(blank=True, help_text='Link for online events', validators=[django.core.validators.URLValidator()])),
                ('requires_registration', models.BooleanField(default=False)),
                ('registration_url', models.URLField(blank=True, help_text='External registration link', validators=[django.core.validators.URLValidator()])),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees (leave blank for unlimited)', null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Recommended size: 800x400 pixels', upload_to='events/')),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO (max 160 characters)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'), models.Index(fields=['is_published'], name='events_even_is_publ_cc4b67_idx'), models.Index(fields=['category'], name='events_even_categor_25d9bd_idx'), models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx')],
            },
        ),
    ]
