# Fly.io configuration for Seventh Day Sabbath Church Of Christ (ShalomGH)
# Optimized for startup budget with auto-sleep and minimal resources

app = "shalomgh"
primary_region = "fra"  # Frankfurt - closest to Ghana and matches DB region
kill_signal = "SIGINT"
kill_timeout = "10s"

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "church_website.settings"
  # Allow Fly domain(s) and internal health check host
  ALLOWED_HOSTS = "shalomgh.fly.dev,.fly.dev,localhost,127.0.0.1,fly-local"
  DEBUG = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0  # Auto sleep when no traffic
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "10s"
    path = "/healthz"
    # Ensure Django sees a permitted Host header during internal checks
    headers = { Host = "shalomgh.fly.dev" }

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "sh -lc 'python manage.py migrate --noinput && python manage.py collectstatic --noinput'"
