# Generated by Django 5.2.4 on 2025-07-29 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ShalomGH', max_length=100)),
                ('church_name', models.CharField(default='Seventh Day Sabbath Church Of Christ', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('welcome_message', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('address', models.TextField(blank=True)),
                ('service_times', models.TextField(blank=True, help_text='Enter service times in HTML format')),
                ('member_portal_url', models.URLField(blank=True, help_text='URL to external member portal', validators=[django.core.validators.URLValidator()])),
                ('giving_platform_url', models.URLField(blank=True, help_text='URL to external giving platform', validators=[django.core.validators.URLValidator()])),
                ('facebook_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('twitter_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('instagram_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('youtube_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO (max 160 characters)', max_length=160)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for SEO')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=100)),
                ('google_analytics_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
