# Generated by Django 5.2.4 on 2025-07-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_section', models.CharField(choices=[('home_hero', 'Home Page Hero Background'), ('home_welcome', 'Home Page Welcome Section'), ('about_hero', 'About Page Hero Background'), ('about_team', 'About Page Team Section'), ('sermons_hero', 'Sermons Page Hero Background'), ('events_hero', 'Events Page Hero Background'), ('ministries_hero', 'Ministries Page Hero Background'), ('contact_hero', 'Contact Page Hero Background'), ('giving_hero', 'Giving Page Hero Background'), ('plan_visit_hero', 'Plan Visit Page Hero Background'), ('beliefs_hero', 'Beliefs Page Hero Background'), ('leadership_hero', 'Leadership Page Hero Background'), ('location_hero', 'Location Page Hero Background'), ('speakers_hero', 'Speakers Page Hero Background'), ('series_hero', 'Sermon Series Page Hero Background'), ('general_church', 'General Church Photos'), ('worship_service', 'Worship Service Photos'), ('community_events', 'Community Events Photos'), ('youth_ministry', 'Youth Ministry Photos'), ('children_ministry', 'Children Ministry Photos'), ('music_ministry', 'Music Ministry Photos')], help_text='Select which page/section this image is for', max_length=50)),
                ('title', models.CharField(help_text='Descriptive title for the image', max_length=200)),
                ('image', models.ImageField(help_text='Upload image (recommended: 1920x1080 for hero images, 800x600 for section images)', upload_to='page_images/')),
                ('fallback_url', models.URLField(blank=True, help_text='Fallback image URL (e.g., from Unsplash) if uploaded image is not available')),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Optional caption for the image')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying multiple images in the same section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Image',
                'verbose_name_plural': 'Page Images',
                'ordering': ['page_section', 'display_order', '-created_at'],
                'unique_together': {('page_section', 'display_order')},
            },
        ),
    ]
