# Generated by Django 5.2.4 on 2025-07-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250730_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(blank=True, default="Join our vibrant community of believers as we worship, grow in faith, and serve with purpose in God's amazing love.", help_text='Subtitle/description displayed below the hero title'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(blank=True, default='Welcome to Our Church Family', help_text='Main title displayed on the homepage hero section', max_length=200),
        ),
    ]
