# Generated by Django 5.2.4 on 2025-07-31 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_hero_subtitle_sitesetting_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='cta_image',
            field=models.ImageField(blank=True, help_text='Image to display in CTA sections (optional)', null=True, upload_to='cta_images/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL to embed in CTA sections (optional)', validators=[django.core.validators.URLValidator()]),
        ),
    ]
