# Generated by Django 5.2.4 on 2025-08-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_cta_image_sitesetting_cta_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the milestone (e.g., 'Years of Service', 'Members Served')", max_length=100)),
                ('value', models.CharField(help_text="The milestone value (e.g., '25+', '1000+', '50')", max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional description of the milestone', max_length=200)),
                ('icon_class', models.CharField(blank=True, help_text="CSS class for icon (e.g., 'fas fa-church', 'fas fa-users')", max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display the milestone (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this milestone on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Key Milestone',
                'verbose_name_plural': 'Key Milestones',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
