# Generated by Django 5.2.4 on 2025-08-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_keymilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_paystack',
            field=models.BooleanField(default=False, help_text='Enable Paystack payment integration'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='paystack_public_key',
            field=models.CharField(blank=True, help_text='Paystack public key for online donations', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='paystack_secret_key',
            field=models.CharField(blank=True, help_text='Paystack secret key (keep this secure)', max_length=100),
        ),
    ]
