# Generated by Django 5.2.4 on 2025-08-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesetting_enable_paystack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the service (e.g., 'Saturday Sabbath Worship')", max_length=100)),
                ('time', models.CharField(help_text="Time of the service (e.g., '10:00 AM - 12:00 PM')", max_length=50)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week for this service', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this service (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service time should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Time',
                'verbose_name_plural': 'Service Times',
                'ordering': ['display_order', 'day'],
            },
        ),
    ]
