# Generated by Django 5.2.4 on 2025-08-01 23:02

from django.db import migrations


def create_default_service_times(apps, schema_editor):
    """Create default service times for the church."""
    ServiceTime = apps.get_model('core', 'ServiceTime')

    # Create default service times
    default_services = [
        {
            'name': 'Saturday Sabbath Worship',
            'day': 'saturday',
            'time': '10:00 AM - 12:00 PM',
            'display_order': 1,
            'is_active': True,
        },
        {
            'name': 'Wednesday Bible Study',
            'day': 'wednesday',
            'time': '7:00 PM - 8:30 PM',
            'display_order': 2,
            'is_active': True,
        },
        {
            'name': 'Friday Prayer Meeting',
            'day': 'friday',
            'time': '7:00 PM - 8:00 PM',
            'display_order': 3,
            'is_active': True,
        },
    ]

    for service_data in default_services:
        ServiceTime.objects.get_or_create(
            name=service_data['name'],
            defaults=service_data
        )


def reverse_create_default_service_times(apps, schema_editor):
    """Remove default service times."""
    ServiceTime = apps.get_model('core', 'ServiceTime')
    ServiceTime.objects.filter(
        name__in=[
            'Saturday Sabbath Worship',
            'Wednesday Bible Study',
            'Friday Prayer Meeting'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servicetime'),
    ]

    operations = [
        migrations.RunPython(
            create_default_service_times,
            reverse_create_default_service_times
        ),
    ]
