# Generated by Django 5.2.4 on 2025-07-29 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('general_overseer', 'General Overseer'), ('assistant_overseer', 'Assistant Overseer'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('minister', 'Minister'), ('pastor', 'Pastor'), ('evangelist', 'Evangelist'), ('teacher', 'Teacher'), ('other', 'Other')], max_length=20)),
                ('custom_position', models.CharField(blank=True, help_text="Use this if position is 'Other'", max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, help_text='Recommended size: 400x400 pixels', upload_to='leadership/')),
                ('years_in_ministry', models.PositiveIntegerField(blank=True, null=True)),
                ('specializations', models.TextField(blank=True, help_text='Areas of ministry specialization')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership Profile',
                'verbose_name_plural': 'Leadership Profiles',
                'ordering': ['display_order', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About Us'), ('our_story', 'Our Story'), ('beliefs', 'Our Beliefs'), ('mission', 'Mission Statement'), ('vision', 'Vision Statement'), ('values', 'Our Values')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO (max 160 characters)', max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ['page'],
            },
        ),
    ]
