# Generated by Django 5.2.4 on 2025-08-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Church Family', help_text='Main title for the welcome section', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle below the main title', max_length=300)),
                ('content', models.TextField(help_text='Main welcome content/description')),
                ('image', models.ImageField(blank=True, help_text='Welcome section image (recommended: 800x600px)', null=True, upload_to='welcome_images/')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the welcome image', max_length=200)),
                ('feature_1_title', models.CharField(default='Bible-Centered Teaching', help_text='First feature title', max_length=100)),
                ('feature_1_description', models.TextField(default="We believe the Bible is God's Word and the foundation for all faith and practice.", help_text='First feature description')),
                ('feature_2_title', models.CharField(default='Authentic Community', help_text='Second feature title', max_length=100)),
                ('feature_2_description', models.TextField(default='We foster genuine relationships where people can grow together in faith.', help_text='Second feature description')),
                ('feature_3_title', models.CharField(default='Compassionate Service', help_text='Third feature title', max_length=100)),
                ('feature_3_description', models.TextField(default='We serve our community and world with the love and compassion of Christ.', help_text='Third feature description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this welcome section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welcome Section',
                'verbose_name_plural': 'Welcome Sections',
            },
        ),
    ]
