# Generated by Django 5.2.4 on 2025-08-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_welcomesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipprofile',
            name='position',
            field=models.CharField(choices=[('general_overseer', 'General Overseer'), ('senior_pastor', 'Senior Pastor'), ('assistant_pastor', 'Assistant Pastor'), ('associate_pastor', 'Associate Pastor'), ('executive_pastor', 'Executive Pastor'), ('worship_pastor', 'Worship Pastor'), ('youth_pastor', 'Youth Pastor'), ('children_pastor', "Children's Pastor"), ('missions_pastor', 'Missions Pastor'), ('outreach_pastor', 'Outreach Pastor'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('deaconess', 'Deaconess'), ('trustee', 'Trustee'), ('minister', 'Minister'), ('evangelist', 'Evangelist'), ('teacher', 'Teacher'), ('prophet', 'Prophet'), ('apostle', 'Apostle'), ('worship_leader', 'Worship Leader'), ('choir_director', 'Choir Director'), ('sunday_school_superintendent', 'Sunday School Superintendent'), ('youth_leader', 'Youth Leader'), ('children_director', "Children's Director"), ('women_ministry_leader', "Women's Ministry Leader"), ('men_ministry_leader', "Men's Ministry Leader"), ('church_administrator', 'Church Administrator'), ('secretary', 'Church Secretary'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('missionary', 'Missionary'), ('chaplain', 'Chaplain'), ('counselor', 'Counselor'), ('other', 'Other')], max_length=50),
        ),
    ]
