# Generated by Django 5.2.5 on 2025-08-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_seed_leadership_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipprofile',
            name='go_card_photo',
            field=models.ImageField(blank=True, help_text='Optional: Use a different photo for the General Overseer card', upload_to='leadership/go_card/'),
        ),
    ]
