# Generated by Django 5.2.4 on 2025-07-29 22:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ministry_type', models.CharField(choices=[('mens', "Men's Ministry"), ('womens', "Women's Ministry"), ('youth', 'Youth & Teens'), ('children', "Children's Church"), ('music', 'Music & Worship'), ('prayer', 'Prayer & Intercession'), ('evangelism', 'Evangelism & Missions'), ('discipleship', 'Discipleship / Small Groups'), ('outreach', 'Community Outreach'), ('education', 'Christian Education'), ('other', 'Other')], default='other', max_length=20)),
                ('short_description', models.CharField(help_text='Brief description for ministry listing', max_length=200)),
                ('description', models.TextField()),
                ('mission_statement', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('meeting_day', models.CharField(blank=True, help_text="e.g., 'Every Sunday', 'First Friday of the month'", max_length=20)),
                ('meeting_time', models.CharField(blank=True, help_text="e.g., '10:00 AM - 12:00 PM'", max_length=50)),
                ('meeting_location', models.CharField(blank=True, max_length=200)),
                ('min_age', models.PositiveIntegerField(blank=True, help_text='Minimum age for participation', null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, help_text='Maximum age for participation (leave blank for no limit)', null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Recommended size: 800x400 pixels', upload_to='ministries/')),
                ('activities', models.TextField(blank=True, help_text='List of activities and programs')),
                ('requirements', models.TextField(blank=True, help_text='Any requirements for joining this ministry')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO (max 160 characters)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_leaders', models.ManyToManyField(blank=True, related_name='assisted_ministries', to='pages.leadershipprofile')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_ministries', to='pages.leadershipprofile')),
            ],
            options={
                'verbose_name': 'Ministry',
                'verbose_name_plural': 'Ministries',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MinistryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended size: 800x600 pixels', upload_to='ministries/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='ministries.ministry')),
            ],
            options={
                'verbose_name': 'Ministry Gallery Image',
                'verbose_name_plural': 'Ministry Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ministry',
            index=models.Index(fields=['ministry_type'], name='ministries__ministr_33ebfa_idx'),
        ),
        migrations.AddIndex(
            model_name='ministry',
            index=models.Index(fields=['is_active'], name='ministries__is_acti_98cd19_idx'),
        ),
        migrations.AddIndex(
            model_name='ministry',
            index=models.Index(fields=['display_order'], name='ministries__display_382434_idx'),
        ),
    ]
